name: Testing MageDBM2
on: [push, pull_request]
jobs:
  build:
   strategy:
     matrix:
       operating-system: [ubuntu-latest]
       php-version: ['7.0', '7.1', '7.2', '7.3', '7.4']
   runs-on: ${{ matrix.operating-system }}
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Setup PHP, with composer and extensions
       uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
       with:
         php-version: ${{ matrix.php-version }}
         extensions: mbstring, simplexml, dom
     
     - name: Run Tests
       run: make test 
